version: '3.8'

services:
  mentortrack:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  # 将来的にPostgreSQLを使いたい場合のオプション（コメントアウト）
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: mentortrack
  #     POSTGRES_USER: mentortrack
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
